### PR TITLE
[junit5] Populate fields for beforeAll() if PER_CLASS

### PR DESCRIPTION
**Pull request by kriegfrj**
This is a prototype of the fix for `BundleContextExtension` for #201, #462.

If we are happy with the approach, I will add it to the other extensions.

@chrisr3, can you take it for a spin and see if it solves your problem to your satisfaction?

### CODE REVIEW

**Comment by chrisr3** [comment]
> @chrisr3, can you take it for a spin and see if it solves your problem to your satisfaction?

My test-case now passes, and so does a larger OSGi-using project that I have. So this looks good to me :+1:.

**Comment by kriegfrj** [comment]
> > @chrisr3, can you take it for a spin and see if it solves your problem to your satisfaction?
> 
> My test-case now passes, and it doesn't break a larger OSGi-using project that I have. So this looks good to me 👍.

Thanks so much for confirming - I'll try and polish it up for merging tomorrow.

**Comment by bjhargrave** [comment]
@kriegfrj Can you finish this PR up? I think we need to proceed to kick off a 1.1 release.

**Comment by kriegfrj** [comment]
I will try to finish this today.

**Comment by kriegfrj** [comment]
Found a couple of unrelated bugs in a couple of extensions while working on this. Will fix these in a separate PR. Should have this done in a couple of hours (would be good to squeeze them into 1.1.0 too).

**Review by bjhargrave — APPROVED** [review]

**Comment by bjhargrave** [comment]
Very nice!

**Comment by kriegfrj** [comment]
> Very nice!

:+1: Thanks for the tidy-ups!

**Pull request merged**
